### ISSUE TITLE
Refuses to open at all

### ISSUE THREAD

**Issue by DrewsephA** [kaydensigh/chromecalclock#12]
Acer Chromebook, "Version 58.0.3029.112 (Official Build) (64-bit)" from chrome://chrome

I'll click on the icon, and nothing happens. I tried from the shelf, from the app launcher, and even the "Launch App" button on the webstore page, nothing works... :\ 

Happy to get whatever other info you need, I really liked this app, it was quick and easy to use.

**Comment by kaydensigh** [comment]
Sorry I haven't looked at this project in a long time.

I think your issue is likely something to do with how Chrome OS displays windows. The app tries to save its window location and open in the same place the next time. If the screen resolution or coordinates (e.g. with multiple windows) changed in the mean time, it might open off screen.

I think there were some attempts at fixing this back in 2017, but its hard to reproduce. If you still see it, try uninstalling the app and re-installing it; that should clear the sync storage.
