### ISSUE TITLE
No cities for India?

### ISSUE THREAD

**Issue by eichmat** [kaydensigh/chromecalclock#8]
Only found one city for India (Kolkata)...  a country with over 1.25-billion people and over 1.2 million square miles in size only gets one entry... and it is the 3rd largest city in India... The capital doesn't even get a mention...  

I mean, you've nailed all the former Soviet Republics in Asia, and several cities in Mongolia, but couldn't get more one from India?

**Comment by kaydensigh** [comment]
The app relies on the [Intl.DateTimeFormat API](https://tc39.github.io/ecma402/#datetimeformat-objects) which uses the [IANA Time Zone Database](https://www.iana.org/time-zones). That database maintains data on distinct time zones each named after a city within that time zone. Unfortunately, since India is all one time zone, the only name appearing in the database is Asia/Kolkata.

There have been suggestions in the past to show a larger number of cities and internally map them to IANA time zone names but I didn't want this app to have to maintain that mapping. There might already be a library that does this and I'd be open to incorporating it into the app. It would need to have translations for the city names though.

As a side note, I agree it's weird that time zones are not named after the most populous city in that zone. I guess there must have been historical or technical reasons for that.
